core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/DateFacetDefinitionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/FacetCollectorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/FacetSearchCollectorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/NumericFacetDefinitionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreFunctionSearchOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreSearchOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchCollector.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchCollectorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchMetaStageDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchStageDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/StringFacetDefinitionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/TextSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/extension/StringListExtension.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/DateFacetDefinitionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/FacetCollectorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/FacetSearchCollectorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/NumericFacetDefinitionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreSearchOptionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/StringFacetDefinitionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/TextSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/util/DocumentExtension.kt

Text operator

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/EqualsSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/EqualsSearchOperatorDslTest.kt

feat: implement equals search operator

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationKtTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/CompoundSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/DateFacetDefinitionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/FacetSearchCollectorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/NumericFacetDefinitionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/StringFacetDefinitionDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/search/text/TextSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/search/text/TextSearchRepositoryTest.kt

Project stage

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PhraseSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PhraseSearchOperatorDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/search/phrase/PhraseSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/search/text/TextSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/search/phrase/PhraseSearchRepositoryTest.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/search/text/TextSearchRepositoryTest.kt

Phrase operator

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/RangeSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/TextSearchOperatorDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/RangeSearchOperatorDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/search/range/RangeSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/search/range/RangeSearchRepositoryTest.kt

Range operator

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/EmbeddedDocumentSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PathSearchOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PhraseSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/TextSearchOperatorDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/EmbeddedDocumentSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PathSearchOptionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PhraseSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/TextSearchOperatorDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/entity/supplies/SaleItem.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/entity/supplies/Sales.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/search/embeddedDocument/EmbeddedDocumentSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/search/embeddedDocument/EmbeddedDocumentSearchRepositoryTest.kt

Embedded operator

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ExistsSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ExistsSearchOperatorDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/entity/sample/FruitQuantities.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/entity/sample/Fruits.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/ExistsSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/ExistsSearchRepositoryTest.kt

feat: implement ExistsSearchOperatorDsl

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoShapeRelation.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoShapeSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PathSearchOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoShapeSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PhraseSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/TextSearchOperatorDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/entity/airbnb/ListingsAndReviews.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/entity/airbnb/ListingsAndReviewsAddress.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/entity/sample/UserAccount.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/entity/sample/Users.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/EqualsSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/GeoShapeSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/GeoShapeSearchRepositoryTest.kt

Geoshape operator

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoShapeSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoWithinSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/CompoundSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/DateFacetDefinitionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/EmbeddedDocumentSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/EqualsSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ExistsSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/FacetSearchCollectorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoShapeSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoWithinSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/NumericFacetDefinitionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PhraseSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/RangeSearchOperatorDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreFunctionSearchOptionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreSearchOptionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchMetaStageDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchStageDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/StringFacetDefinitionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/TextSearchOperatorDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/GeoWithinSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/GeoWithinSearchRepositoryTest.kt

implement geoWithin operator

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ExtendedSortOperation.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/SortStageDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/SortStageDslTest.kt

implement Sort stage

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDslTest.kt

Sort by count

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ExtendedLookupOperation.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/LookupStageDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreFunctionSearchOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreSearchOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/mapping/KPropertyPath.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/LookupStageDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreFunctionSearchOptionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreSearchOptionDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/LookupRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/ScoreSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/LookupRepositoryTest.kt

implement Lookup stage

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PathSearchOptionDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/UnsetRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/UnsetRepositoryTest.kt

implement Unset stage

---

.github/workflows/ci.yml
build.gradle.kts
config/detekt/detekt.yml
core/build.gradle.kts
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ExtendedLookupOperation.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ExtendedSortOperation.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/SortStageDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/EmbeddedDocumentSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoShapeSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/GeoWithinSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/QueryStringQueryOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/RangeSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreFunctionSearchOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/ScoreSearchOptionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchCollector.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/extension/MongoTemplateExtension.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/extension/StringListExtension.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/mapping/KPropertyPath.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ProjectStageDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/PathSearchOptionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/QueryStringQueryOptionDslTest.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/extension/AtlasTestConstructorExtension.kt
libs.versions.toml

apply Detekt

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/RegexSearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/RegexSearchOperatorDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/RegexSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/RegexSearchRepositoryTest.kt

Implement RegexSearchOperatorDsl

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/AutocompleteSearchOperationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/AutocompleteTokenOrder.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperator.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/SearchOperatorDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/TokenOrder.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/search/AutocompleteSearchOperationDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/AutocompleteSearchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/AutocompleteSearchRepositoryTest.kt

Autocomplete search operator

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/SortRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/AutocompleteSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/EmbeddedDocumentSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/GeoShapeSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/GeoWithinSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/MoreLikeThisSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/NearSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/PhraseSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/QueryStringSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/RangeSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/ScoreSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/SortSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/TextSearchRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/atlas/WildcardSearchRepository.kt

Add operation $skip $limit

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/AggregationExpressionDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/AggregationExpressionDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/GroupRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/MatchRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/MatchRepositoryTest.kt

implement match stage

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/AggregationExpressionDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/AggregationExpressionDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/LiteralExpressionRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/LiteralExpressionRepositoryTest.kt

Implement literal operator expression

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/LookupStageDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/AggregationExpressionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/variable/LetExpressionDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/LookupStageDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/variable/LetExpressionDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/LookupRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/LetExpressionRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/LetExpressionRepositoryTest.kt

implement variable expression

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/AggregationExpressionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/conditional/CondExpressionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/conditional/IfNullExpressionDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/conditional/SwitchExpressionDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/conditional/CondExpressionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/conditional/IfNullExpressionDslTest.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/conditional/SwitchExpressionDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/CondExpressionRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/IfNullExpressionRepository.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/SwitchExpressionRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/CondExpressionRepositoryTest.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/IfNullExpressionRepositoryTest.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/expression/SwitchExpressionRepositoryTest.kt

resolves #84 
---
Hi, master. 
Among the codes I wrote, the `$switch` operator has not yet written the sample code.
I want to check the `$switch` operator code I designed first and proceed to the next.

Implement Conditional Expression Operators

---

core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/AggregationDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ReplaceRootDsl.kt
core/src/main/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/expression/AggregationExpressionDsl.kt
core/src/test/kotlin/com/github/inflab/spring/data/mongodb/core/aggregation/ReplaceRootDslTest.kt
example/spring-data-mongodb/src/main/kotlin/com/github/inflab/example/spring/data/mongodb/repository/ReplaceRootRepository.kt
example/spring-data-mongodb/src/test/kotlin/com/github/inflab/example/spring/data/mongodb/repository/ReplaceRootRepositoryTest.kt

Implemet $repalceRoot stage dsl
